### PR TITLE
Add red theme html

### PR DESCRIPTION
**Pull request by doodthedoodthedood**

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
Where is the CSS? I only see the HTML file

**Comment by MasterOfTheTiger** [comment]
Looks good! Merging.

**Comment by doodthedoodthedood** [comment]
Great!

**Comment by MasterOfTheTiger** [comment]
For the next couple weeks I am not going to be able to write any code. I still might be able to merge pull requests though. So please keep up the good work! Make an issue if you want to see something added, and if we think that is a good idea, to ahead and work on it and make a pull request. Thanks for your help!

**Comment by doodthedoodthedood** [comment]
Np! I am starting to get how to use github, so that is good. For the issue thing, if I think of something, I will write it asap!

**Comment by MasterOfTheTiger** [comment]
Good. We are open to all sorts of ideas. Also, we have some features we want to add in issues if you want to work on them. Ones marked “release” are very important to get done soon.

**Comment by doodthedoodthedood** [comment]
Okay. I just got an idea. What if we could do highlighting? I could make that really easily(maybe). In updates then we could add more colors.

**Comment by MasterOfTheTiger** [comment]
Highlighting is going to be made when we have user accounts set up. Otherwise people could easily lose their highlights. When we get that working then you can work on the front end for it. Right now maybe you can work on bookmarking? There is a issue with more information.

**Comment by doodthedoodthedood** [comment]
Okay, I will look at it. PS do you know that the read me shows your irl name?

**Comment by MasterOfTheTiger** [comment]
Yes I know.

**Comment by MasterOfTheTiger** [comment]
Also, it is not my real name...... I never use my real name online.

**Comment by doodthedoodthedood** [comment]
Just wanted to let you know

**Comment by doodthedoodthedood** [comment]
Oh. Okay then

**Comment by MasterOfTheTiger** [comment]
Also. Next time can you upload screenshots to the pull request? Thanks.

**Pull request merged**
